#include <iostream>
#include <vector>
#include <cstring>
#define O_o (
#define o_O )
#define Z_Z *
#define t_t *=
#define QAQ +
#define c_c ++
#define Y_Y ,
#define o_o -
#define e_e --
#define C_C -=
#define T3T .
#define x0x 1
#define x_x ;
#define Q3Q <
#define QWQ <<
#define n_n <=
#define D3D =
#define Y3Y >
#define p_p >=
#define S3S >>
#define M3M MAXM
#define h_h MAXN
#define B3B [
#define I_I ]
#define E_E cin
#define r_r const
#define P3P cout
#define R_R endl
#define K3K for
#define i_i int
#define y_y main
#define L3L max
#define B_B memset
#define F_F min
#define G_G namespace
#define O_O push_back
#define J_J return
#define S_S size
#define q_q sizeof
#define b_b std
#define I3I struct
#define J3J using
#define U_U vector
#define z_z while
#define m_m {
#define f_f }
J3J G_G b_b x_x r_r i_i h_h D3D O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o x0x QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O x_x r_r i_i M3M D3D O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o O_o x0x QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QWQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O x_x i_i V_V B3B M3M I_I Y_Y u_u B3B M3M I_I Y_Y N3N B3B M3M I_I x_x I3I X_X m_m i_i H3H Y_Y v_v Y_Y g_g x_x f_f x_x U_U Q3Q X_X Y3Y H_H B3B O_o O_o O_o O_o O_o O_o O_o x0x QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O QAQ x0x o_O QWQ x0x o_O I_I x_x i_i C3C Y_Y N_N x_x i_i y_y O_o o_O m_m i_i j_j Y_Y a_a D3D x0x x_x X_X s_s x_x E_E S3S C3C S3S N_N x_x K3K O_o i_i A_A D3D 0x0 x_x A_A Q3Q C3C x_x A_A c_c o_O m_m E_E S3S s_s T3T H3H S3S s_s T3T v_v S3S j_j S3S s_s T3T g_g x_x a_a D3D L3L O_o a_a Y_Y j_j o_O x_x H_H B3B j_j I_I T3T O_O O_o s_s o_O x_x f_f K3K O_o i_i R3R D3D 0x0 x_x R3R n_n a_a x_x R3R c_c o_O m_m B_B O_o N3N Y_Y 0x0 Y_Y q_q O_o N3N o_O o_O x_x K3K O_o i_i A_A D3D 0x0 x_x A_A Q3Q H_H B3B R3R I_I T3T S_S O_o o_O x_x A_A c_c o_O m_m K3K O_o i_i U3U D3D 0x0 x_x U3U n_n N_N x_x U3U c_c o_O u_u B3B U3U I_I D3D V_V B3B U3U I_I x_x i_i L_L D3D x0x x_x z_z O_o L_L o_O m_m i_i H3H D3D H_H B3B R3R I_I B3B A_A I_I T3T H3H Z_Z L_L x_x i_i g_g D3D H_H B3B R3R I_I B3B A_A I_I T3T g_g Z_Z L_L x_x K3K O_o i_i U3U D3D N_N x_x U3U p_p H3H x_x U3U e_e o_O u_u B3B U3U I_I D3D L3L O_o u_u B3B U3U I_I Y_Y u_u B3B U3U o_o H3H I_I QAQ g_g o_O x_x H_H B3B R3R I_I B3B A_A I_I T3T v_v C_C L_L x_x L_L t_t O_o x0x QWQ x0x o_O x_x L_L D3D F_F O_o L_L Y_Y H_H B3B R3R I_I B3B A_A I_I T3T v_v o_O x_x f_f K3K O_o i_i U3U D3D 0x0 x_x U3U n_n N_N x_x U3U c_c o_O N3N B3B U3U I_I D3D L3L O_o N3N B3B U3U I_I Y_Y u_u B3B U3U I_I o_O x_x f_f K3K O_o i_i U3U D3D 0x0 x_x U3U n_n N_N x_x U3U c_c o_O V_V B3B U3U I_I D3D L3L O_o V_V B3B U3U I_I Y_Y N3N B3B U3U I_I o_O x_x f_f P3P QWQ V_V B3B N_N I_I QWQ R_R x_x J_J 0x0 x_x f_f
